[package]
name = "rshijack"
version = "0.3.0"
description = "tcp connection hijacker, rust rewrite of shijack"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/rshijack"
categories = ["command-line-utilities"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "kpcyrd/rshijack" }

[dependencies]
structopt = "0.3.14"
pnet = "0.26"
env_logger = "0.7"
log = "0.4"
anyhow = "1.0"
pktparse = "0.5"
